community/urls.py
from django.urls import path
from . import views
from . import views2

app_name = 'community'
urlpatterns = [
    # /community/
    path('', views.index, name='index'),
    path('discover', views.discover, name='discover'),
    path('discover/<int:community_tag>', views.detail, name='detail'),

    path('v2', views2.index, name='index2'),
    path('v2/discover', views2.discover, name='discover2'),
    path('v2/discover/<int:community_tag>', views2.detail, name='detail2'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('community.urls'))
]

community/models.py
from django.db import models
import django.utils.timezone as timezone


class Result(models.Model):
    #log_filename = models.CharField(max_length=250, default='con050217.csv')
    log_filename = models.CharField(max_length=250)
    start_time = models.CharField(max_length=100, default='2018-05-02T17:00')
    end_time = models.CharField(max_length=100, default='2018-05-02T17:01')
    smallest_size = models.IntegerField(default=2)
    interval = models.IntegerField(default=60)
    ordinal_number = models.IntegerField(default=1)
    formatted_args = models.CharField(max_length=100, default="")
    link_counts = models.IntegerField(default=0)
    community_counts = models.IntegerField(default=0)
    ip_counts = models.IntegerField(default=0)
    result_time = models.DateTimeField(default=timezone.now())
    result_filename = models.CharField(primary_key=True, max_length=200,
                                       default='con050217.csv_2018-05-02T1700_2018-05-02T1701_2.csv')

    def __str__(self):
        return str(self.result_filename) + ' -- ' + str(self.result_time)


class Community(models.Model):
    result = models.ForeignKey(Result, on_delete=models.CASCADE)
    community_tag = models.IntegerField(primary_key=True, default=-1)
    leader_ip = models.CharField(max_length=20, default='')
    ip_counts = models.IntegerField(default=0)
    link_counts = models.IntegerField(default=0)
    purity = models.FloatField(default=0)
    apps = models.CharField(max_length=512, default='')

    def __str__(self):
        return '{},{},{},{}'.format(self.community_tag, self.leader_ip, self.ip_counts, self.link_counts)

community/views.py
# coding:utf8
from __future__ import unicode_literals
from pyecharts import Graph, Bar
from django.shortcuts import render
import time
import os
import pandas as pd
from sklearn.cluster import DBSCAN
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, StandardScaler
from .models import Result, Community
import numpy as np
import django.utils.timezone as timezone
from collections import Counter
from django.core.exceptions import ObjectDoesNotExist

PROJECT_DIR = os.path.dirname(__file__)
DATA_SET_DIR = os.path.join(PROJECT_DIR, "static/community/dataset")
RESULT_DIR = os.path.join(PROJECT_DIR, "static/community/result")
if not os.path.exists(RESULT_DIR):
    os.makedirs(RESULT_DIR)

# 至少有这么IP对才会做聚类操作
LEAST_IP_PAIR_FOR_CLUSTERING = 3


def index(request):
    """
    使用最近一次发现结果渲染页面

    :param request:
    :return:
    """
    # if Result.objects.all():
    #     last_result = Result.objects.latest('result_time')
    #     df, last_result, communities = get_result_df(log_filename=last_result.log_filename,
    #                                                  start_time=last_result.start_time,
    #                                                  end_time=last_result.end_time,
    #                                                  smallest_size=last_result.smallest_size)
    #     g = get_graph(df)
    # else:
    print('index')
    last_result = Result()
    g = get_graph(pd.DataFrame())
    communities = {}

    context = dict(
        graph=g.render_embed(),
        files=os.listdir(DATA_SET_DIR),
        last_result=last_result,
        communities=communities
    )

    return render(request, 'community/discover.html', context)


def get_graph(df):
    """
    根据发现结果df生成关系图

    :param df: df
    :return:
    """
    print('get_graph')
    links = []
    exist_nodes = {}

    for i in df.index:
        source = df.loc[i, 'ip1']
        target = df.loc[i, 'ip2']
        if source not in exist_nodes:
            exist_nodes[source] = []
        if target not in exist_nodes:
            exist_nodes[target] = []
        exist_nodes[source].append(int(df.loc[i, 'community_tag']))
        exist_nodes[target].append(int(df.loc[i, 'community_tag']))
        links.append({'source': source, 'target': target})
    nodes = []
    categories = []
    for node, cato_list in exist_nodes.items():
        # 取众数
        cat = Counter(cato_list).most_common(1)[0][0]
        nodes.append({'name': node, 'symbolSize': 10, 'value': cat})
        categories.append(cat)
    categories = LabelEncoder().fit_transform(categories)
    for node, cat in zip(nodes, categories):
        node['category'] = cat
    g = Graph(title="拓扑结构", subtitle='IP:{} Links:{}'.format(len(nodes), len(links)), width=800, height=600)
    g.add("", nodes, links, layout='circular', categories=list(categories))
    return g


def get_result_df(log_filename, start_time, end_time, smallest_size):
    """
    根据指定参数得到发现结果表，如果已有则读取，没有则计算得到

    :param log_filename:
    :param start_time:
    :param end_time:
    :param smallest_size:
    :return:
    """
    print('get_result_df')
    result_filename = '{}_{}_{}.csv'.format(log_filename, start_time, end_time).replace(':', '')
    if os.path.exists(os.path.join(RESULT_DIR, result_filename)):
        df = pd.read_csv(os.path.join(RESULT_DIR, result_filename))
        # 移除小社团
        df = remove_small_community(df, smallest_size=smallest_size)

        try:
            result = Result.objects.get(result_filename__exact=result_filename)
        except ObjectDoesNotExist:
            result = Result()
            result.end_time = end_time
            result.start_time = start_time
            result.log_filename = log_filename
            result.community_counts = len(set(df['community_tag']))
            result.ip_counts = len(set(df['ip1']) | set(df['ip2']))
            result.result_filename = result_filename

        result.result_time = timezone.now()
        result.smallest_size = smallest_size
        result.save()

    else:
        # 读入
        df = read_log(log_filename, start_time, end_time)
        # df.to_csv(os.path.join(RESULT_DIR, '{}_df1.csv'.format(result_filename)), index=False)
        # 清洗
        df = wash_log(df)
        # df.to_csv(os.path.join(RESULT_DIR, '{}_df2.csv'.format(result_filename)), index=False)
        # 节点区分
        df = partition_entities(df)
        # df.to_csv(os.path.join(RESULT_DIR, '{}_df3.csv'.format(result_filename)), index=False)
        # 边分区
        df = partition_links(df)
        # df.to_csv(os.path.join(RESULT_DIR, '{}_df4.csv'.format(result_filename)), index=False)
        # 交换IP使领袖节点在同一列
        df = exchange_fields(df)
        # df.to_csv(os.path.join(RESULT_DIR, '{}_df5.csv'.format(result_filename)), index=False)
        # 对拓扑相似的边聚类
        df = group_and_cluster(df)
        # df.to_csv(os.path.join(RESULT_DIR, '{}_df6.csv'.format(result_filename)), index=False)
        # 标签重编码
        df = encode_tag(df)
        df.to_csv(os.path.join(RESULT_DIR, result_filename), index=False)
        # 移除小社团
        df = remove_small_community(df, smallest_size=smallest_size)

        result = Result()
        result.result_time = timezone.now()
        result.smallest_size = smallest_size
        result.end_time = end_time
        result.start_time = start_time
        result.log_filename = log_filename
        result.community_counts = len(set(df['community_tag']))
        result.ip_counts = len(set(df['ip1']) | set(df['ip2']))
        result.result_filename = result_filename
        result.save()

    communities = set()
    for community_tag, community_table in df.groupby('community_tag'):
        community = Community(community_tag=community_tag)
        community.result = result
        community.ip_counts = len(set(community_table['ip1']) | set(community_table['ip2']))
        community.link_counts = community_table.shape[0]
        community.leader_ip = community_table['ip2'].mode()[0]
        community.purity = Counter(community_table['app']).most_common(1)[0][1]/len(community_table['app'])
        # community.save()
        communities.add(community)
    communities = sorted(communities, key=lambda c: c.ip_counts, reverse=True)

    return df, result, communities


def discover(request):
    """
    展示发现结果

    :param request:
    :return: 渲染后的页面
    """
    print('discover')
    log_filename = request.POST['filename']
    start_time = request.POST['start_time']
    end_time = request.POST['end_time']
    smallest_size = request.POST['smallest_size']
    df, last_result, communities = get_result_df(log_filename=log_filename, start_time=start_time, end_time=end_time,
                                                 smallest_size=smallest_size)
    g = get_graph(df)
    context = dict(
        graph=g.render_embed(),
        files=os.listdir(DATA_SET_DIR),
        communities=communities,
        last_result=last_result,

    )
    return render(request, 'community/discover.html', context)


def get_hist(df, community_tag, feature_cols):
    """
    生成柱形图

    :param df:
    :param community_tag:
    :param feature_cols:
    :return:
    """
    # feature_cols = ['port1','port2','proto',
    #                 'pkts12_min','pkts12_mid','pkts12_max',
    #                 'pkts21_min','pkts21_mid','pkts21_max',
    #                 'pkl12_min','pkl12_mid','pkl12_max',
    #                 'pkl21_min','pkl21_mid','pkl21_max']
    print('get_hist')

    community_table = df[df['community_tag'] == community_tag].copy()[feature_cols]
    axis_min = int(community_table.values.min())
    axis_max = int(community_table.values.max())
    bar = Bar("")
    for col in feature_cols:
        values_counts = community_table[col].value_counts()
        for i in range(axis_min-1, axis_max + 2):
            if i not in values_counts.index:
                values_counts.loc[i] = 0
        values_counts = values_counts.sort_index()
        bar.add(col, values_counts.index, values_counts.values, legend_pos='center', legend_top='bottom', is_datazoom_show=True,
                datazoom_type='slider')
    return bar


def detail(request, community_tag):
    """
    某个社团的详细信息

    :param request:
    :param community_tag:
    :return:
    """
    print('detail')
    last_result = Result.objects.latest('result_time')
    df, last_result, communities = get_result_df(log_filename=last_result.log_filename,
                                                 start_time=last_result.start_time,
                                                 end_time=last_result.end_time,
                                                 smallest_size=last_result.smallest_size)
    feature_groups = [
        ['port1', 'port2'],
        ['proto'],
        ['pkts12_min', 'pkts12_mid', 'pkts12_max'],
        ['pkts21_min', 'pkts21_mid', 'pkts21_max'],
        ['pkl12_min', 'pkl12_mid', 'pkl12_max'],
        ['pkl21_min', 'pkl21_mid', 'pkl21_max']
    ]
    bars = []
    for feature_cols in feature_groups:
        bars.append(get_hist(df, community_tag, feature_cols).render_embed())
    graph = get_graph(df[df['community_tag'] == community_tag]).render_embed()
    context = dict(
        graph=graph,
        bars=bars,
        community_tag=community_tag,
        communities=communities
    )

    return render(request, 'community/detail.html', context)


def read_log(filename, start_time, end_time):
    """
    读取指定时间区间的日志

    :param filename: 文件名
    :param start_time: "2018-05-02T17:00"
    :param end_time:
    :return: DataFrame log_df
    """
    print('read_log')
    useful_columns = ['ip1', 'ip2', 'port1', 'port2', 'proto', 'pkts12', 'pkts21', 'bytes12', 'bytes21', 'etime',
                      'class', 'app']
    log_df = pd.read_csv(os.path.join(DATA_SET_DIR, filename), usecols=useful_columns, encoding='gbk')
    log_df['class'] = log_df['app']
    start_time = time.mktime(time.strptime(start_time, "%Y-%m-%dT%H:%M"))
    end_time = time.mktime(time.strptime(end_time, "%Y-%m-%dT%H:%M"))

community/templates/community/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>社团发现</title>
    {% load staticfiles %}
    <script src="{% static 'lib/jquery.min.js' %}"></script>
    <script src="{% static 'lib/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/bootstrap.min.css' %}"/>
    <script src="{% static 'lib/echarts.min.js' %}"></script>
</head>

<body>
{% block body %}
{% endblock %}
</body>

</html>

community/templates/community/detail.html
{% extends 'community/base.html' %}
{% load staticfiles%}
{%block body%}
<div class="container">

  <h1>社团{{ community_tag }}</h1>
{{graph}}
{% for bar in bars %}
  {{bar}}
{% endfor %}

  <table class="table table-striped table-responsive w-75 p-3" >
    <thead class="thead-dark">
    <tr>
      <th class="col-md-3 text-center">编号</th>
      <th class="col-md-3 text-center">领袖IP</th>
      <th class="col-md-3 text-center">总IP数</th>
      <th class="col-md-3 text-center">总边数</th>
    </tr>
    </thead>
    {% for c in communities %}
    <tr class="text-center">
      <td class="col-md-3"><a href="{% url 'community:detail' c.community_tag %}">社团{{c.community_tag}}</a></td>
      <td class="col-md-3">{{c.leader_ip}}</td>
      <td class="col-md-3">{{c.ip_counts}}</td>
      <td class="col-md-3">{{c.link_counts}}</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

community/templates/community/detail2.html
{% extends 'community/base.html' %}
{% load staticfiles%}
{%block body%}
<div class="container">

  <h1>社团{{ community_tag }}</h1>
{{graph}}

  {% for bar in bars %}
<div>
  {{bar}}
</div>
{% endfor %}

  <table class="table table-striped table-responsive w-75 p-3" >
    <thead class="thead-dark">
    <tr>
      <th class="col-md-3 text-center">编号</th>
      <th class="col-md-3 text-center">领袖IP</th>
      <th class="col-md-3 text-center">总IP数</th>
      <th class="col-md-3 text-center">总边数</th>
    </tr>
    </thead>
    {% for c in communities %}
    <tr class="text-center">
      <td class="col-md-3"><a href="{% url 'community:detail' c.community_tag %}">社团{{c.community_tag}}</a></td>
      <td class="col-md-3">{{c.leader_ip}}</td>
      <td class="col-md-3">{{c.ip_counts}}</td>
      <td class="col-md-3">{{c.link_counts}}</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}

community/templates/community/discover.html
{% extends 'community/base.html' %}
{% load staticfiles%}
{%block body%}
<div class="container">
    <nav>
        <form class="form-horizontal container" action="{% url 'community:discover' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label>文件：</label>
                <select name="filename">
                    <option value="{{last_result.log_filename}}">{{last_result.log_filename}}</option>
                    {% for f in files %}
                    <option value="{{f}}">{{f}}</option>
                    {% endfor %}
                </select>
                &nbsp&nbsp
                <label>起始时间：</label>
                <input name="start_time" type="datetime-local" value="{{last_result.start_time}}"/>
                &nbsp&nbsp
                <label>终止时间：</label>
                <input name="end_time" type="datetime-local" value="{{last_result.end_time}}"/>
                &nbsp&nbsp
                <label>最小IP数：</label>
                <input name="smallest_size" pattern="[0-9]+" type="text" value="{{last_result.smallest_size}}" />
                &nbsp&nbsp
                <input type="submit" class="btn btn-primary"/>
            </div>
        </form>
    </nav>
{{graph}}
<div class="container w-75 p-3">
  <table class="table table-striped table-responsive w-75 p-3" >
    <thead class="thead-dark">
      <tr>
        <th class="col-md-3 text-center">编号</th>
        <th class="col-md-3 text-center">领袖IP</th>
        <th class="col-md-3 text-center">总IP数</th>
        <th class="col-md-3 text-center">纯度</th>
      </tr>
    </thead>
    {% for c in communities %}
      <tr class="text-center">
        <td class="col-md-3"><a href="{% url 'community:detail' c.community_tag %}">社团{{c.community_tag}}</a></td>
        <td class="col-md-3">{{c.leader_ip}}</td>
        <td class="col-md-3">{{c.ip_counts}}</td>
        <td class="col-md-3">{{c.purity|floatformat:'2'}}</td>
      </tr>
    {% endfor %}
  </table>
</div>
</div>
{% endblock %}

community/templates/community/discover2.html
{% extends 'community/base.html' %}
{% load staticfiles%}
{%block body%}
<div class="container">
<!--div-->

    <form class="form-horizontal container" action="{% url 'community:discover2' %}" method="post"
          enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label>文件：</label>
        <select name="filename">
            <option value="{{last_result.log_filename}}">{{last_result.log_filename}}</option>
            {% for f in files %}
            <option value="{{f}}">{{f}}</option>
            {% endfor %}
        </select>
        &nbsp&nbsp
        <label>算法：</label>
        <select name="algorithm">
            <option value="{{ algorithms.0 }}">{{ algorithms.0 }}</option>
            {% for a in algorithms %}
            <option value="{{a}}">{{a}}</option>
            {% endfor %}
        </select>
        &nbsp&nbsp
        <label>参数：</label>
        <input name="args" type="text" value="{{last_result.args}}"/>
        &nbsp&nbsp
        <label>时间间隔：</label>
        <input name="interval" pattern="[0-9]+" type="text" value="{{last_result.interval}}"/>
        &nbsp&nbsp
        <label>序数：</label>
        <input name="ordinal_number" pattern="[0-9]+" type="text" value="{{last_result.ordinal_number}}"/>
        <!--
        <label>起始时间：</label>
        <input name="start_time" type="datetime-local" value="{{last_result.start_time}}"/>
        &nbsp&nbsp
        <label>终止时间：</label>
        <input name="end_time" type="datetime-local" value="{{last_result.end_time}}"/>
        &nbsp&nbsp
        <label>最小IP数：</label>
        <input name="smallest_size" pattern="[0-9]+" type="text" value="{{last_result.smallest_size}}" />
        -->
        &nbsp&nbsp
        <input type="submit" class="btn btn-primary"/>
    </div>
</form>
{{graph}}
<div class="container w-75 p-3">
  <table class="table table-striped table-responsive w-75 p-3" >
    <thead class="thead-dark">
      <tr>
        <th class="col-md-3 text-center">编号</th>
        <th class="col-md-3 text-center">领袖IP</th>
        <th class="col-md-3 text-center">总IP数</th>
        <th class="col-md-3 text-center">总边数</th>
        <th class="col-md-3 text-center">应用类型</th>
      </tr>
    </thead>
    {% for c in communities %}
      <tr class="text-center">
        <td class="col-md-3"><a href="{% url 'community:detail2' c.community_tag %}">社团{{c.community_tag}}</a></td>
        <td class="col-md-3">{{c.leader_ip}}</td>
        <td class="col-md-3">{{c.ip_counts}}</td>
        <td class="col-md-3">{{c.link_counts}}</td>
        <td class="col-md-3">{{c.apps}}</td>
      </tr>
    {% endfor %}
  </table>
</div>
</div>
{% endblock %}

community/templates/community/pyecharts.html
{% extends 'community/base.html' %}
{% load staticfiles%}
{%block body%}
<div class="container">

    <form class="form-horizontal container" action="{% url 'community:discover' %}" method="post"
          enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label>文件：</label>
        <select name="filename">
            <option value="{{last_result.log_filename}}">{{last_result.log_filename}}</option>
            {% for f in files %}
            <option value="{{f}}">{{f}}</option>
            {% endfor %}
        </select>
        &nbsp&nbsp
        <label>起始时间：</label>
        <input name="start_time" type="datetime-local" value="{{last_result.start_time}}"/>
        &nbsp&nbsp
        <label>终止时间：</label>
        <input name="end_time" type="datetime-local" value="{{last_result.end_time}}"/>
        &nbsp&nbsp
        <label>最小IP数：</label>
        <input name="smallest_size" pattern="[0-9]+" type="text" value="{{last_result.smallest_size}}" />
        &nbsp&nbsp
        <input type="submit" class="btn btn-primary"/>
    </div>
</form>
{{graph}}
<div class="container w-75 p-3">
  <table class="table table-striped table-responsive w-75 p-3" >
    <thead class="thead-dark">
      <tr>
        <th class="col-md-3 text-center">编号</th>
        <th class="col-md-3 text-center">领袖IP</th>
        <th class="col-md-3 text-center">总IP数</th>
        <th class="col-md-3 text-center">总边数</th>
      </tr>
    </thead>
    {% for c in communities %}
      <tr class="text-center">
        <td class="col-md-3"><a href="{% url 'community:detail' c.community_tag %}">社团{{c.community_tag}}</a></td>
        <td class="col-md-3">{{c.leader_ip}}</td>
        <td class="col-md-3">{{c.ip_counts}}</td>
        <td class="col-md-3">{{c.link_counts}}</td>
      </tr>
    {% endfor %}
  </table>
</div>
{% endblock %}